### ISSUE TITLE
Extend README

### ISSUE THREAD

**Issue by olexandr-konovalov** [ZachNewbery/try-gap-in-deepnote#1]
Nice to have in README:
- [x] a phrase explaining what Deepnote is and a link to https://deepnote.com/
- [x] instructions to use this as a template for an own project, like https://github.com/rse-standrewscs/gap-binder-template
- [x] What are the limitations of the GAP installation it uses (not all packages compiled), how to address them?

**Comment by ZachNewbery** [comment]
Updated in #7 - this will likely have to be reopened when a new base docker container is created (particularly for the second task) as it would simplify the templating process by a lot
