### ISSUE TITLE
Remembering using local Dockerfile

### ISSUE THREAD

**Issue by olexandr-konovalov** [ZachNewbery/try-gap-in-deepnote#2]
Copying @nathancarter's comment from https://github.com/gap-system/try-gap-in-jupyter/issues/5
> Is there no way to configure a project so that it remembers the correct container in which the project should be run? That is, can we get to the point where the user can skip the step of opening the environment tab and manually rebuilding the container?

**Comment by olexandr-konovalov** [comment]
need to start reading the docs from https://docs.deepnote.com/environment/custom-environments and https://docs.deepnote.com/environment/custom-environments/running-your-own-kernel

**Comment by ZachNewbery** [comment]
Fixed in #8 -- this does satisfy the defaulting of Dockerfiles since it is duplicating a project, but does require the user to click the "Duplicate" button after clicking the "Launch in Deepnote" badge.
