### ISSUE TITLE
Changing base Docker container

### ISSUE THREAD

**Issue by olexandr-konovalov** [ZachNewbery/try-gap-in-deepnote#5]
It now starts from `deepnote/python:3.7`, because the GAP container installed Python packages incompatible with Deepnote.  It may be worth to create a separate GAP container for Deepnote, to avoid building GAP and packages each time here.

**Comment by ZachNewbery** [comment]
I believe I may need someone with access to the gapsystem docker account/namespace to publish the image? So that consistency is kept between the other GAP docker images instead of having a base container like zachnewbery/gap-deepnote

**Comment by olexandr-konovalov** [comment]
There is now a new repository https://github.com/gap-system/gap-docker-deepnote/ to work on this separate container.

**Comment by ZachNewbery** [comment]
#9 adds a deprecation notice and a link to this new repo.
